#!/bin/bash
#
echo
echo "   \033[36m Autoinstaller für Bigwolf200-Tools\033[0m"
echo
echo "   \033[36m Author:     Wolf2000\033[0m"
echo "   \033[36m Version:         1.0\033[0m"
echo "   \033[36m https://wolf2000.at\033[0m"
echo
cd &&
sleep 1 &&
git clone https://github.com/Wolf2000Pi/bigwolf2000-tools.git &&
sleep 1
cd bigwolf2000-tools &&
sleep 1
chmod +x install-bigwolf2000-tools.sh &&
sleep 1
./install-bigwolf2000-tools.sh
